Press refresh
open-sauced/landing-page pull request #46
Opened 2022-09-26 12:27 UTC by shamimbinnur

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This is the new UI refresh for the https://opensauced.pizza/press
Now every logo has two buttons to download in both SVG and PNG formats.

Deploy preview link: https://deploy-preview-46--opensauced-landing.netlify.app/press

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

![Screenshot 2022-09-26 at 6 29 51 PM](https://user-images.githubusercontent.com/48399373/192276554-dec0b2fb-441d-4a77-b480-fc3ab3eba174.png)
![Screenshot 2022-09-26 at 6 30 02 PM](https://user-images.githubusercontent.com/48399373/192276579-256d8cf4-5334-4339-a102-ca4d5e5f338c.png)

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2022-09-27 17:51 UTC, NsdHSO commented on components/OpenSaucedLogo.tsx
> +    <div className='w-full tablet:max-w-[290px]'>
```suggestion
    <div className='w-full tablet:max-w-xs'>
```

max-w-xs = 320px

2022-09-27 17:53 UTC, NsdHSO commented on components/OpenSaucedLogo.tsx
> +        <div className={`flex h-[164px] w-full justify-center items-center ${ isBlackBG ? "bg-black" : "bg-none"} ` }>
```suggestion
        <div className={`flex h-40 w-full justify-center items-center ${ isBlackBG ? "bg-black" : "bg-none"} ` }>
```

h-40 = 160px

2022-09-27 17:54 UTC, NsdHSO commented on components/OpenSaucedLogo.tsx
> +            <div className='h-[100px] w-auto'>
```suggestion
            <div className='h-24 w-auto'>
```

h-24 = 96px
h-28 = 112px

2022-09-27 17:54 UTC, NsdHSO commented on components/OpenSaucedLogo.tsx
> +                <img className='w-full h-full ' src={svgLogo} alt={title} />
```suggestion
                <img className='w-full h-full' src={svgLogo} alt={title} />
```

2022-09-27 17:55 UTC, NsdHSO commented on components/OpenSaucedLogo.tsx
> +        <div className='mt-[20px]'>
```suggestion
        <div className='mt-5'>
```

mt-5 = 20px

2022-09-27 18:02 UTC, NsdHSO requested changes
Please where you use px replace with classes from tailwind. 
Please take a look here where @bdougie created this [issue](https://github.com/open-sauced/hot/issues/267)

2022-09-27 18:32 UTC, 0-vortex commented
Good catches @NsdHSO LGTM with those changes 👍

2022-09-28 18:34 UTC, 0-vortex approved these changes
LGTM! 👍

2022-09-28 20:56 UTC, bdougie requested changes
We need to move towards reusable tailwinds classes and away from hardcoding px and rems

2022-09-28 20:56 UTC, bdougie commented on components/PressHeading.tsx
> +    <div className='py-[4rem] tablet:py-[8rem]'>
these rems need to be replaced with tailwinds classes. i.e. `py-2` or whatever the closest. 

There was a tweet that describes why this is important recently. https://twitter.com/t3dotgg/status/1574906239993028610

2022-09-28 20:56 UTC, bdougie commented on components/PressHeading.tsx
> +        <h1 className='text-white font-bold tracking-tight mb-2 text-[2rem] tablet:text-[3rem]'>{title}</h1>
don't use rems. use classes

2022-09-28 20:56 UTC, bdougie commented on components/OpenSaucedLogo.tsx
> +            <p className='text-[1rem] tracking-tight text-gray-700'>{description}</p>
remove rems and px. use native tailwinds class

2022-09-28 20:56 UTC, bdougie commented on components/OpenSaucedLogo.tsx
> +                <button className='text-white text-[18px] font-semibold bg-gradient-to-r px-4 py-1 rounded-md from-orange-500 to-orange-400'>PNG</button>
remove px

2022-09-28 21:12 UTC, shamimbinnur commented
@bdougie I am gonna try rewriting the code and replacing it with classes as much as possible to do. We might still need to use rem in some cases tho.

2022-09-29 14:45 UTC, bdougie commented
> We might still need to use rem in some cases tho.

Need to know why and justification in the comments. Need to consider rems is the equivalent to `!mportant`. Should be used sparingly.

2022-10-05 21:17 UTC, merged